### ISSUE TITLE
Front camera not opening in iOS OS version 16.4 

### ISSUE THREAD

**Issue by bharthik** [hiukim/mind-ar-js#370] opened 2023-04-01 15:51 UTC
The camera automatically switches to the rear camera in iOS 16.4

**Comment by wuiyang** [comment] 2023-04-12 16:07
This is caused by invalid media track constraints used to get front facing camera.

AFrame:
https://github.com/hiukim/mind-ar-js/blob/41e3e264c6861c45512364d724c620412cc67180/src/face-target/aframe.js#L105

ThreeJS:
https://github.com/hiukim/mind-ar-js/blob/41e3e264c6861c45512364d724c620412cc67180/src/face-target/three.js#L107


Should use `'user'` instead of `'face'`

Reference:
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/facingMode

**Comment by sharimken** [comment] 2023-04-30 14:26
any solution for this?
I tried modifying to "user" in "mindar-facec-aframe.prod.js" but still no luck on iPad with 16.4.1.

**Comment by hiukim** [comment] 2023-05-01 02:30
really? I don't think that "," has any effect. It's a valid syntax.

You have error running the code with ","?

**Comment by sharimken** [comment] 2023-05-01 06:09
> really? I don't think that "," has any effect. It's a valid syntax.
> 
> You have error running the code with ","?

I don’t see any error, but seems likely only iOS16.4 or later will trigger this bug. My last modification only fixed safari, not Google Chrome.

*The facingMode does trigger this bug on the latest iOS, I remembered that I tried removing facing mode completely, it seems fixing Google Chrome bug too. I will verify it again later tonight.

**Comment by sanriomisintaro** [comment] 2023-05-18 07:04
I'm struggling with this problem, but this is my solution,.

in mindar-face-aframe.prod.js file
instead of using face or user. I change both, so I don't use environment
default: 'face': 'environment'
solution: 'face': 'user'

because of that code, I can't use my external webcam when using my laptop (which has a front camera).
This could be a temporary solution.

**Comment by Makio64** [comment] 2023-06-02 09:20
> really? I don't think that "," has any effect. It's a valid syntax.
> 
> You have error running the code with ","?

the answer confuse me too, @wuiyang means  

Change From :
`facingMode: (this.shouldFaceUser ? 'face' : 'environment'), `

To :
`facingMode: (this.shouldFaceUser ? 'user' : 'environment'), `

in [mind-ar-js/src/face-target/aframe.js](https://github.com/hiukim/mind-ar-js/blob/41e3e264c6861c45512364d724c620412cc67180/src/face-target/aframe.js#L105) & [mind-ar-js/src/face-target/three.js](https://github.com/hiukim/mind-ar-js/blob/41e3e264c6861c45512364d724c620412cc67180/src/face-target/three.js#L107)

**Comment by hiukim** [comment] 2023-06-04 09:09
fixed in v1.2.2. thx

**Closed by hiukim** 2023-06-04 09:09 UTC
